[package]
name = "zkleanpool"
type = "bin"
version = "0.1.0"

[dependencies]
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
keccak256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/keccak256" }