root = [173, 18, 51, 190, 30, 61, 180, 228, 199, 75, 151, 118, 124, 173, 16, 144, 40, 102, 213, 220, 186, 152, 98, 31, 92, 230, 96, 161, 229, 57, 217, 191]
nullifier_hash = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 16, 5, 123, 202, 67, 189, 158, 14, 239, 60, 207, 110, 19, 39]
secret = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 92, 129, 25, 233, 19, 93, 177, 53, 15, 241, 208]
nullifier = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 195, 249]
path_elements = [
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 254, 116, 177, 82, 59, 233, 161, 138, 118, 104, 102, 188, 7, 32, 89],
  [37, 184, 93, 3, 140, 117, 6, 2, 221, 96, 50, 231, 48, 51, 129, 61, 188, 149, 165, 242, 127, 254, 172, 68, 23, 106, 37, 72, 73, 71, 173, 255],
  [107, 19, 0, 16, 222, 241, 195, 127, 21, 248, 76, 31, 35, 211, 124, 171, 11, 239, 184, 168, 134, 105, 40, 200, 186, 3, 247, 253, 67, 132, 69, 130],
  [204, 51, 237, 117, 182, 25, 55, 240, 12, 246, 101, 17, 55, 51, 243, 105, 16, 25, 166, 95, 99, 161, 218, 29, 74, 38, 77, 202, 75, 118, 249, 75],
  [239, 90, 83, 162, 173, 61, 143, 103, 171, 105, 9, 119, 71, 217, 64, 77, 144, 220, 169, 204, 3, 228, 221, 74, 148, 25, 215, 145, 213, 171, 203, 120],
  [222, 255, 246, 211, 48, 187, 84, 3, 246, 59, 20, 243, 59, 87, 130, 116, 22, 13, 227, 165, 13, 244, 239, 236, 240, 224, 219, 115, 188, 221, 61, 165],
  [97, 123, 221, 17, 247, 192, 161, 31, 73, 219, 34, 246, 41, 56, 122, 18, 218, 117, 150, 249, 209, 112, 77, 116, 101, 23, 124, 99, 216, 142, 199, 215],
  [41, 44, 35, 169, 170, 29, 139, 234, 126, 36, 53, 229, 85, 164, 166, 14, 55, 154, 90, 53, 243, 244, 82, 186, 230, 1, 33, 7, 63, 182, 238, 173],
  [225, 206, 169, 46, 217, 154, 205, 203, 4, 90, 103, 38, 178, 248, 113, 7, 232, 166, 22, 32, 162, 50, 207, 77, 125, 91, 87, 102, 179, 149, 46, 16],
  [122, 214, 108, 10, 104, 199, 44, 184, 158, 79, 180, 48, 56, 65, 150, 110, 64, 98, 167, 106, 185, 116, 81, 227, 185, 251, 82, 106, 92, 235, 127, 130],
  [224, 38, 204, 90, 74, 237, 60, 34, 165, 140, 189, 61, 42, 199, 84, 201, 53, 44, 84, 54, 246, 56, 4, 45, 202, 153, 3, 78, 131, 99, 101, 22],
  [61, 4, 207, 253, 139, 70, 168, 116, 237, 245, 207, 174, 99, 7, 125, 232, 95, 132, 154, 102, 4, 38, 105, 123, 6, 168, 41, 199, 13, 209, 64, 156],
  [173, 103, 106, 163, 55, 164, 133, 228, 114, 138, 11, 36, 13, 146, 179, 239, 123, 60, 55, 45, 6, 209, 137, 50, 43, 253, 95, 97, 241, 231, 32, 62],
  [162, 252, 164, 164, 150, 88, 249, 250, 183, 170, 99, 40, 156, 145, 183, 199, 182, 200, 50, 166, 208, 230, 147, 52, 255, 91, 10, 52, 131, 208, 157, 171],
  [78, 191, 217, 205, 123, 202, 37, 5, 247, 190, 245, 156, 193, 193, 46, 204, 112, 143, 255, 38, 174, 74, 241, 154, 190, 133, 42, 254, 158, 32, 200, 98],
  [45, 239, 16, 209, 61, 209, 105, 245, 80, 245, 120, 189, 163, 67, 217, 113, 122, 19, 133, 98, 224, 9, 59, 56, 10, 17, 32, 120, 157, 83, 207, 16],
  [119, 106, 49, 219, 52, 161, 160, 167, 202, 175, 134, 44, 255, 223, 255, 23, 137, 41, 127, 250, 220, 56, 11, 211, 211, 146, 129, 211, 64, 171, 211, 173],
  [226, 231, 97, 11, 135, 165, 253, 243, 167, 46, 190, 39, 18, 135, 217, 35, 171, 153, 14, 239, 172, 100, 182, 229, 157, 121, 248, 183, 224, 140, 70, 227],
  [80, 67, 100, 165, 198, 133, 139, 249, 143, 255, 113, 74, 181, 190, 157, 225, 158, 211, 26, 151, 104, 96, 239, 189, 14, 119, 42, 46, 254, 35, 226, 224],
  [79, 5, 244, 172, 184, 63, 91, 101, 22, 141, 159, 239, 137, 213, 109, 77, 119, 184, 148, 64, 21, 230, 177, 238, 216, 27, 2, 56, 226, 208, 219, 163],
]
path_indices = [
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
]